name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check:
    name: check
    runs-on: ubuntu-26.04
    container: fedora:43
    env:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    steps:
      - uses: actions/checkout@v7

      - name: Install RPM tooling
        run: dnf install -y glibc-langpack-en dnf-plugins-core git rpmlint rpmdevtools rpm-build 'dnf-command(builddep)'

      - name: Enable COPR build dependencies
        run: dnf copr enable -y iolaum/aitoolkit

      - name: Install spec build dependencies
        run: |
          for file in */*.spec; do
            dnf builddep -y "${file}"
          done

      - name: Run rpmlint
        run: |
          for file in */*.spec; do
            rpmlint "${file}" --strict
          done

      - name: Build RPMs
        run: |
          for file in */*.spec; do
            spectool -Rg "${file}"
            rpmbuild -ba "${file}"
          done
